### ISSUE TITLE
Release checklist 5.0

### ISSUE THREAD

**Issue by raphaelm** [opacapp/opacclient#456]
- [x] Thoroughly test opacdata integration
  - [x] Background service
  - [x] Library list activity
    - [x] Timeout
  - [x] Manual refreshing
  - [x] ACRA integration
- [x] Merge #450 
- [x] Thoroughly test account view
  - [x] With covers
  - [x] Without covers
- [x] Find a way to build 5.0 on F-Droid (if it doesn't work)
- [ ] Handle remaining support requests
- [x] Put library configuration files into a public repository under opacapp/
